export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
