export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER";
export const DETELE_CUSTOMER = "DETELE_CUSTOMER";
export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER";
